from django.urls import path
from deal_app.properties.api.views import (
    PropertyIncomeCreateAPIView,
    PropertyIncomeRetrieveUpdateDestroyAPIView,
    PropertyListCreateAPIView,
    PropertyRetrieveUpdateDestroyAPIView,
    PropertyPurchaseCreateAPIView,
    PropertyPurchaseRetrieveUpdateDestroyAPIView
)
from deal_app.properties.views import (
    property_list_view,
    property_detail_view,
    property_update_view,
    property_delete_view,
    property_income_update_view,
    property_purchase_update_view,
    property_create_view
)

app_name = "properties"
urlpatterns = [
    path(
        '<int:pk>/',
        view=property_detail_view,
        name="detail"
    ),
    path(
        '',
        view=property_list_view,
        name="list"
    ),
    path(
        "create/",
        view=property_create_view,
        name="create-property"
    ),
    path(
        "update/<int:pk>",
        view=property_update_view,
        name="update-basic-info"
    ),
    path(
        "update-income/<int:pk>/",
        view=property_income_update_view,
        name="update-income"
    ),
    path(
        "edit-purchase/<int:pk>/",
        view=property_purchase_update_view,
        name="edit-purchase"
    ),
    path(
        "<int:pk>/delete/",
        view=property_delete_view,
        name="delete"
    ),
    path(
        'api/property/',
        view=PropertyListCreateAPIView.as_view(),
        name='property-create-api'
    ),
    path(
        'api/<int:uuid>/property/',
        view=PropertyRetrieveUpdateDestroyAPIView.as_view(),
        name='property-rud-api'
    ),
    path(
        'api/property-income/',
        view=PropertyIncomeCreateAPIView.as_view(),
        name='property-income-create-api'
    ),
    path(
        'api/<int:uuid>/property-income/',
        view=PropertyIncomeRetrieveUpdateDestroyAPIView.as_view(),
        name='property-income-rud-api'
    ),
    path(
        'api/property-purchase/',
        view=PropertyPurchaseCreateAPIView.as_view(),
        name='property-purchase-create-api'
    ),
    path(
        'api/<int:uuid>/property-purchase/',
        view=PropertyPurchaseRetrieveUpdateDestroyAPIView.as_view(),
        name='property-purchase-rud-api'
    )
]
